### ISSUE TITLE
Problem with mothur biom file

### ISSUE THREAD

**Issue by Cupplesam** [KasperSkytte/ampvis2#100]
I am having trouble using the following command with my mothur biom file. The error message  is below. Any suggestions would be appreciated, thanks so much for your time.

amp_import_biom(file)

Error: Can't combine `..1$Kingdom` <logical> and `..2$Kingdom` <factor<01553>>.
Run `rlang::last_error()` to see where the error occurred.
In addition: Warning message:
Taxonomy had less than 7 levels for all OTU's (Kingdom->Species), filling with NA from Species level and up.

**Comment by KasperSkytte** [comment]
Hi

Please provide a reproducible example.

**Comment by welinda1** [comment]
I have the same issue for a while!  I can no longer import biom files that used to work. I suspect that the problem was caused by updates because I can't use it since the installations. Found a similar problem reported on GitHub : [https://github.com/knausb/vcfR/issues/159](https://github.com/knausb/vcfR/issues/159) [https://github.com/knausb/vcfR/issues/159#issuecomment-636526057](url) that was traced back to R and dplyr updates in spring.

Error: Can't combine `..1$Kingdom` <logical> and `..2$Kingdom` <character>.
Run `rlang::last_error()` to see where the error occurred.
In addition: Warning message:
Taxonomy had less than 7 levels for all OTU's (Kingdom->Species), filling with NA from Species level and up.
> rlang::last_error()
<error/vctrs_error_incompatible_type>
Can't combine `..1$Kingdom` <logical> and `..2$Kingdom` <character>.
Backtrace:
 1. ampvis2::amp_import_biom("mypath/myfile.biom")
 4. vctrs::vec_default_ptype2(...)
 5. vctrs::stop_incompatible_type(...)
 6. vctrs:::stop_incompatible(...)
 7. vctrs:::stop_vctrs(...)
Run `rlang::last_trace()` to see the full context.
> rlang::last_trace()
<error/vctrs_error_incompatible_type>
Can't combine `..1$Kingdom` <logical> and `..2$Kingdom` <character>.
Backtrace:
    x
 1. +-ampvis2::amp_import_biom("mypath/myfile.biom")
 2. | \-dplyr::bind_rows(taxSkeleton, tax)
 3. |   \-vctrs::vec_rbind(!!!dots, .names_to = .id)
 4. \-vctrs::vec_default_ptype2(...)
 5.   \-vctrs::stop_incompatible_type(...)
 6.     \-vctrs:::stop_incompatible(...)
 7.       \-vctrs:::stop_vctrs(...)

**Comment by KasperSkytte** [comment]
I think I would need your exact biom file or a subset thereof for debugging, I cannot reproduce the error on my end.

**Comment by KasperSkytte** [comment]
Hi

The issue should now be fixed. Please see #113
