### ISSUE TITLE
species_nlabels 

### ISSUE THREAD

**Issue by nielsenmaja** [KasperSkytte/ampvis2#13]
Hej 
Jeg er lidt usikker på hvad termen 'extreme' henviser til i nedenstående.

species_nlabels Number of the most extreme species labels to plot (Only makes sense with PCA/RDA).

Er der tale om mest abundante eller dækker det over andet?
Hvorledes bestemmes 'most extreme' species?

På forhånd mange tak.

**Comment by KasperSkytte** [comment]
Answering in english for others to benefit.

A somewhat simplified explanation is that the most extreme species (OTU's) with PCA/RDA is the ones with the biggest influence on the observed differences, where extreme simply means the most distant points with the highest numerical values of both the x and y coordinates. With PCA/RDA these are often OTU's generally abundant in numerous samples, since the OTU's are directly weighted by abundance. Unlike fx Correspondence Analysis, the goal of PCA/RDA is to show the highest numerical variance in the data, which is hereby represented by 'the most extreme' points on the plot.

Hope this explains your question
