### ISSUE TITLE
amp_heatmap tax_show does not handle vector input correctly

### ISSUE THREAD

**Issue by SorenKarst** [KasperSkytte/ampvis2#34]
amp_heatmap returns an error when tax_show is a character vector.

**Comment by KasperSkytte** [comment]
You can only use `"all"` or a number for the `x` most abundant taxa.

**Comment by Jlustermans** [comment]
so there is no way (or workaround) to input a string with genera into amp_heatmap?

**Comment by KasperSkytte** [comment]
@Jlustermans Don't remember why this was closed with no comments. But you can give it a vector of taxa, and they must match exactly as displayed in the heatmap after processing. Alternatively just filter taxa with `amp_filter_taxa` first. The difference between the two is that you can decide the order with `tax_show`, otherwise they will be ranked by abundance. There is also the `order_y_by` option, but that only sets factor levels and you must supply the same amount of taxa in the desired order.

``` r
library("ampvis2")
#> Loading required package: ggplot2
amp_heatmap(
  AalborgWWTPs,
  group_by = "Year",
  tax_aggregate = "Genus"
)
```

![](https://i.imgur.com/IUFiPWV.png)

``` r
amp_heatmap(
  AalborgWWTPs,
  group_by = "Year",
  tax_aggregate = "Genus",
  tax_show = c("Propionicimonas", "Rhodobacter")
)
```

![](https://i.imgur.com/Ngd2ckF.png)

``` r
amp_heatmap(
  amp_filter_taxa(
    AalborgWWTPs,
    c("g__Propionicimonas", "g__Rhodobacter")
  ),
  group_by = "Year",
  tax_aggregate = "Genus"
)
#> 9402 OTUs have been filtered 
#> Before: 9430 OTUs
#> After: 28 OTUs
#> Warning: There are only 2 taxa, showing all
```

![](https://i.imgur.com/UQgTQtH.png)

<sup>Created on 2022-10-14 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>
