### ISSUE TITLE
Shiny doesnt work for plotting:  An error has occurred. Check your logs or contact the app author for clarification.

### ISSUE THREAD

**Issue by arsilan324** [KasperSkytte/ampvis2#49]
Hi,

I am trying to use shiny ampvis2 but it doesnt work. The data does load correcttly but when I try to plot clicking on Analysis tab and then heatmap/boxplot, it gives error. I have arranged all the data as per provided examples and get the same error. I even tried to use the sample data and return to same error. Can you comment on it.

Thanks!
Arslan

**Comment by KasperSkytte** [comment]
Hi @arsilan324. I see the problem, looking into it now.

**Comment by arsilan324** [comment]
Hi Kasper, 
Thank you for the reply. Still getting the same error. I am using CSV separator as semicolon and CSV decimal as comma. Any suggestion?
Thanks

**Comment by KasperSkytte** [comment]
I think the reason is that shinyapps.io has changed something internally, I haven't updated the app for weeks. Apparantly temporary files are not allowed anymore. But you can always run it on your local machine as described [here](https://github.com/KasperSkytte/Amplicon-visualiser#amplicon-visualiser).

**Comment by KasperSkytte** [comment]
Hi again @arsilan324. It seems to work now, thank you for letting us know. Let me know if you still have issues.
