### ISSUE TITLE
"Getting Started"

### ISSUE THREAD

**Issue by sabahzero** [KasperSkytte/ampvis2#50]
This fantastic! I wish I about it sooner, but am glad it exists and am definitely using it now.

The Read Me instructions for downloading ampvis2 work on any version v3.4.1 or later
install.packages("remotes")
remotes::install_github("MadsAlbertsen/ampvis2")

This is not the case if one tries by
install.packages("ampvis2")

May be repetitive, but possibly worth adding a note on the Getting Started page.

Thanks for this!

Sabah

**Comment by sabahzero** [comment]
(you'll probably be getting a bunch of these from me, hopefully they're more helpful and less of a nuisance!)

Suggestion: for the amp_load() function, 
Have last 7 columns, consider replacing Kingdom with Domain as (in personal opinion) this is a more accurate term for current taxonomy. Alternatively, have 8 columns? (Kingdom, Domain, ...etc)

**Comment by sabahzero** [comment]
Suggestion: for the amp_load function,
May be worth tweaking for being able to use one, large metadata table for multiple amplicon datasets. For example, I created a new metadata table as a subset of a larger metadata table since it seems the function automatically considers the first column to be the sample name? 

I like that there's an output specifically requesting the last seven columns for the otu table be  "x, y, z,.... taxa" etc. Potentially adjust this to be a similar output for the metadata tables?

**Comment by KasperSkytte** [comment]
Hi Sabah!

Thanks for the ideas. 

Only packages submitted to the CRAN repository can be installed with `install.packages()`. We will stick with GitHub because updates are instantly available, with CRAN it can take months.
 
I agree on Domain vs Kingdom, but this column is never used during the analysis anyways, and since the OTU table is generated with a specific primer set, it will rarely contain more than one of either Bacteria or Archaea. 

Regarding sample metadata, the format is described alongside that of the OTU table [here](https://madsalbertsen.github.io/ampvis2/reference/amp_load.html). It is simply a table containing information (columns) about each sample (rows), and to match it with additional tables (OTU read counts and taxonomy) it needs to have an identifier between the two, and we decided that the first column should contain the sample ID's/names, the additional columns then contain the metadata. `amp_load` will try to find matches between the two and only keep those, any unmatched samples in either of the tables cannot be used by the plotting functions anyways. But you can always load the complete data at once into one object, and create subset objects of that afterwards, that's the idea behind the `amp_subset*` functions. Or just keep the complete metadata loaded as a data frame in the global environment for reference..

**Comment by sabahzero** [comment]
Hi Kasper, 

Thanks for the reply!

I do think it'd be worth updating to Domain if it's not too much trouble (I did this later on in the code and am happy to share the final version of it with you via my account when it's ready). 

And yes, I did see the format. Though it still may be helpful. Thank you for the clarifications!

Sabah
