### ISSUE TITLE
ampvis2 with phyloseq objects 

### ISSUE THREAD

**Issue by blancaverag** [KasperSkytte/ampvis2#57]
I have been using ampvis2 for a while now and successfully loading data through amp_load. 
Today, I have just read [here](http://madsalbertsen.github.io/ampvis/examples/ampvis_guide.html) that ampvis works on phyloseq objects.

However, if I try to run an ampvis2 function on a phyloseq object (GM), I've got an data format error. 

```
amp_ordinate(data = GM, type="RDA", constrain="Site")
Error: The provided data is not in ampvis2 format. Use amp_load() to load your data before using ampvis2 functions. (Or class(data) <- "ampvis2", if you know what you are doing.)
```

Is there really a way to use ampvis directly on phyloseq objects or data need to be transformed before using ampvis?

Thank you!

**Comment by KasperSkytte** [comment]
Hi there!

There is a big difference between `ampvis` and `ampvis2` by how the data is handled. `ampvis` was using `phyloseq` to handle the data, but is no longer maintained or developed. `ampvis2` is the successor to `ampvis`, however, and uses a somewhat simpler data format, a list of data frames of class `ampvis2`, which is created and returned by the `amp_load` function (the `ampvis2` version of it, of course). So you cannot directly use `ampvis2` functions on `phyloseq` class objects, but you can convert the `phyloseq` object into an `ampvis2` class object instead as described [here](https://madsalbertsen.github.io/ampvis2/articles/faq.html#loading-phyloseq-objects) and proceed normally.
You can of course still install and use the old `ampvis` package, but I wouldn't recommend that. A lot has changed and bugs have been fixed in `ampvis2`. 
Regarding `amp_ordinate`, beware that the `hellinger` transformation is the default in `ampvis2` rather than a simple square root transformation as in `ampvis`. See for example [Legendre & Gallagher, 2001](http://adn.biol.umontreal.ca/~numericalecology/Reprints/Legendre_&_Gallagher.pdf) and [GUSTA ME](https://mb3is.megx.net/gustame/reference/transformations) for details.

Regards
Kasper
