### ISSUE TITLE
Add colored side bar to heatmap

### ISSUE THREAD

**Issue by afmbafmb** [KasperSkytte/ampvis2#66]
Hi,

I am trying to add a side bar to the columns in heatmap to denote different categories of samples. Something similar to the picture below (done with pheatmap). Is it possible to do it in ampvis2?

![pheatmap_anno-768x768](https://user-images.githubusercontent.com/47299148/58297046-c87d3e00-7e08-11e9-8f0c-c6a1bd232af5.png)

Thanks in advance!

**Comment by KasperSkytte** [comment]
Hi

It is not possible directly in `amp_heatmap`, but adding clustering trees like that has been on the list for a while, just haven't got to it since noone requested it. But to add a column like that, you have to generate a ggplot2 plot separately and combine the two plots using fx https://github.com/thomasp85/patchwork

**Comment by afmbafmb** [comment]
Hi Kasper,

Thanks for your reply. Hope you can include it in your future updates.
