### ISSUE TITLE
Is it possible to add species plot for NMDS ordination using amp_ordinate?

### ISSUE THREAD

**Issue by vbalanus** [KasperSkytte/ampvis2#79]
In `vegan` package it is possible to add sample and species coordinates to an NMDS ordination. NMDS of amp_ordinate is based on vegan, so it would be nice to add dominant species to the plot.
Now, if you using
`data("AalborgWWTPs")`
`amp_ordinate(AalborgWWTPs,
             type = "NMDS",
             transform = "none",
             distmeasure = "bray",
             ,species_plot = T)`
I got the the following error message:
`Error: Speciesscores are not available.`

If it would be possible in later versions to include species scores in amp_ordinate for NMDS, I would be very glad.

**Comment by KasperSkytte** [comment]
Hi there

`amp_ordinate` checks whether `vegan::metaMDS` returns species scores, if it does it would just plot them, otherwise you get that error. It's not always it's possible for vegan to generate them, I don't know why.

Regards
Kasper

**Comment by vbalanus** [comment]
Dear Kasper,
 Thanks for your reply, but that is the point, I do not understand.

data("AalborgWWTPs")
amp_ordinate(AalborgWWTPs, type = "NMDS", transform = "none", distmeasure =
"bray" ,species_plot = T)
AA=metaMDS(t(AalborgWWTPs$abund))

I've got the error message:

Error: Speciesscores are not available.


But for
  AA=metaMDS(t(AalborgWWTPs$abund))
species scores are available: AA$species

So it is not a problem from vegan.
 I'd be glad, if you can help ;-)
 Best regards:
  Balázs



Balázs Vajna, PhD, assistant professor
Department of Microbiology
Eötvös Loránd University, Budapest, Hungary

Homepage: mikrobiologia.elte.hu/?q=en/node/111


Kasper Skytte Andersen <notifications@github.com> ezt írta (időpont: 2019.
okt. 14., H, 12:35):

**Comment by KasperSkytte** [comment]
Hi again

I think I found out why. Will make an update soon.

**Comment by vbalanus** [comment]
Hi Kasper,
 Thanks I'll be curious, what is the reason for that!

Kasper Skytte Andersen <notifications@github.com> ezt írta (időpont: 2019.
okt. 16., Sze, 9:24):

**Comment by KasperSkytte** [comment]
I have made some commits to fix the issue. It's because the distance matrix was calculated explicitly before using `metaMDS`, so only a symmetrical matrix with distances between samples were passed on to `metaMDS`, hence species scores were lost. I made it so in the past to support more distance measures like UniFrac, but also because I couldn't understand why setting `distance = "bray"` in `metaMDS` would yield very different results compared to when calculated manually first using fx `vegdist(method = "bray")`. But I now know why, see https://github.com/vegandevs/vegan/issues/332.
